version: '3.9'

services:
  bot:
    container_name: bot
    build:
      dockerfile: docker/web/Dockerfile
      context: .
    ports:
      - "8443:8443"
    command: scripts/web/startup.sh -m -l
    restart: on-failure
    env_file:
      - conf/.env
    volumes:
      - .:/code

    networks:
      - fast_calendar


networks:
  fast_calendar:
    external: True